/*~ Type definitions for t9n
 *~ Definitions generated by: generateTypes.ts */

export type TranslationArgs =
  | ['pageOne.headline']
  | ['pageTwo.description', { params: { params: string } }]
  | ['pageTwo.headline', { params: { with: string; two: string } }];
